apiVersion: ring.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: featureB
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: featureB
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - web
    - web-secured
  match: PathPrefix(`/query/v1`) && Headers(`x-ring`, `featureB`)
  selector:
  # Target deployment instances
    # name of microservice
    name: query
    # Major version of microservice
    version: v1
    # Branch name
    ring: featureB