apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api
            - --accesslog
            - --entrypoints=Name:http Address::8000
            - --entrypoints=Name:https Address::4443
            - --entrypoints=Name:internal Address::8010
            - --providers.kubernetescrd
            # - --providers.kubernetescrd.trace
          ports:
            - name: http
              containerPort: 8000
            - name: https
              containerPort: 4443
            - name: internal
              containerPort: 8010
            - name: admin
              containerPort: 8080