apiVersion: apps/v1
kind: Deployment
metadata:
  name: ring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ring-operator
  template:
    metadata:
      labels:
        name: ring-operator
    spec:
      serviceAccountName: ring-operator
      containers:
        - name: ring-operator
          # Replace this with the built image name
          image: migolfi.azurecr.io/ring-operator:v0.0.1-v1alpha1
          command:
          - ring-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ring-operator"
      imagePullSecrets:
        - name: azurecr
