apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ring-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ring-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - rings.microsoft.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - traefik.containo.us
  resources:
  - 'ingressroutes'
  verbs:
  - '*'